service: bow-wow-backend

plugins:
  - serverless-plugin-typescript
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-appsync-plugin
  - serverless-appsync-offline

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: SECRET

custom:
  accountId: SECRET
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        endpoint: "http://localhost:8000"
        region: localhost
  appSync:
    name: bow-wow-app
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: schema.graphql
    userPoolConfig:
      awsRegion: SECRET
      defaultAction: ALLOW
      userPoolId: SECRET
    dataSources:
      - type: AMAZON_DYNAMODB
        name: bw_datas
        description: 'Bow-Wow Datas'
        config:
          tableName: 'bow-wow'
          serviceRoleArn: SECRET

functions:
  graphql:
    handler: handler.graphql
