service: bow-wow-backend

package:
  individually: true

plugins:
  - serverless-plugin-typescript
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-appsync-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:USERS_TABLE}"

custom:
  accountId: ${env:AWS_ACCOUNT_ID}
  appsync-offline:
    port: 62222
    dynamodb:
      client:
        endpoint: "http://localhost:8000"
        region: localhost
  appSync:
    name: bow-wow-app
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: schema.graphql
    userPoolConfig:
      awsRegion: ${env:AWS_REGION}
      defaultAction: ALLOW
      userPoolId: ${env:AWS_USER_POOL_ID}
    mappingTemplates:
      - dataSource: Users
        type: Query
        field: createUser
        request: "createUser-request-mapping-template.txt"
        response: "createUser-response-mapping-template.txt"
      - dataSource: Users
        type: Query
        field: createPet
        request: "createPet-request-mapping-template.txt"
        response: "createPet-response-mapping-template.txt"
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Users
        description: 'User Datas'
        config:
          tableName: User
          serviceRoleArn: "arn:aws:dynamodb:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:table/${env:USERS_TABLE}"

functions:
  handler:
    handler: handler.main
    events:
      - http:
          path: user
          method: get
          cors: true
          authorizer: aws_iam